### ISSUE TITLE
Sign up not required?

### ISSUE THREAD

**Issue by wetneb** [OAButton/unified-extension#24]
This repo looks great, one extension to rule them all!
I wonder if you would consider waving the registration requirement? Is it really that important? Other buttons such as the Google Scholar button or Lazy Scholar don't require signing up (although they do not provide the same functionality, granted) and I think that's a massive gain in usability.

**Comment by markmacgillivray** [comment]
Not signing up is certainly a massive gain in usability. But I do not think it fits at all with what oabutton wants to achieve - that is, having request "petitions" to authors to make their content freely available. This is different from just finding content that is already available somewhere, and particularly different from ensuring such content is available legally (which does not matter so much to an individual researcher, but does matter to an institution).

Without signing up, there is no personalisation to the request sent to an author - we cannot say to them, this other person wants access in order to do more good things. We could still say some people in general want access, but I do not think that has the same impact when making a direct request.

However, requiring signup is not something I am strongly committed to. Probably you would have to work to convince @JosephMcArthur to drop it though, and I would not get rid of signup, now that we do have it, without clear exposition of the impact upon the core use case, which is (now) requesting authors directly via a petition to make content available.

**Comment by JosephMcArthur** [comment]
Away at the moment, so not totally thinking this through. But here is my
first reaction.

We could move sign up back (any more than an email). As long as we can
identify unique users via the plugin we can still track finds and users.

Details from sign up are only essential for requests. We could take a just
in time approach and only ask for what we need when we need it. Since it
seems data requests need more info from users than articles this could be a
good thing.

That way we balance increased useablity and easier in boarding with what we
need. However, this feels complex to code/design for and I think we may
have bigger challenges right now.

sent from my phone, please excuse any typos.

**Comment by wetneb** [comment]
Yes, that's my point: being able to look for full texts without logging in would be useful, I think. People might first use the app like that, first without signing up, and one day they will want to use it to request papers and sign up for that. But sure, that was just an idea, it's clearly not urgent :-)

**Comment by markmacgillivray** [comment]
This is being added to the new plugin - availability can be retrieved whether signed in or not, then users are recommended to sign in to get the request and other features. Not live yet, but will close as being done now. Good idea! Should drive more users to the plugin, and let's us collect more data even if people do not want an account.

**Comment by JosephMcArthur** [comment]
Mark, have you kept in the email for sign up? I think that's the only thing I'd really push to keep for a basic sign up. That or we need good ways to bug them for their email at a later date.
